# Generated by Django 6.0.1 on 2026-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_cap', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
