# Generated by Django 6.0.1 on 2026-01-14 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_datarefreshstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarefreshstatus',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
