# Generated by Django 6.0.1 on 2026-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_datarefreshstatus_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoprice',
            name='coingecko_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
